### ISSUE TITLE
getRoles: pass in params for additional flexibility

### ISSUE THREAD

**Issue by azhang** [yanickrochon/rbac-a#5]
https://github.com/azhang/rbac-a/commit/096c0c7c9d4c2c7d1cb2f79c78f0a9a12ebd2466

I'm using provider.getRoles() to gather all a user's roles from several different db collections/tables. For example, a user may have `postCreator` inside a specific `post.rbac_users[user1].roles`, and `pageEditor` inside a `page.rbac_users[user1].roles`. However, when I'm checking for permissions inside a `post` namespace (eg. `post:delete`), I don't need to query the db for this user's roles in the `page` table. The number of namespaces can increase infinitely, while the far most common use case is checking just 1 namespace.

In my specific use case, the params I pass in for `attributes` is for namespace control (so that if the user has `postCreator` role, the attribute only enables it for that 1 post). Using the same params, getRoles implementations can have the option to skip unnecessary operations such as querying the `page` collection/table when all we're checking is if the user has a `post` permission.

I hope that makes sense!

**Comment by yanickrochon** [comment]
Right, I see. Because you are using a compound provider, it is unnecessary to check certain roles in certain db (i.e. providers) because you know it won't be there, right? For this reasonly, `getRoles(user)` is insufficient to filter out if a provider really needs to be query or not.

Well, sure, I guess the proposed change is alright. `params` is a user-defined value, may be used however a provider wish, and has no consequence over the core implementation.

As long as people don't substitute this behavior with attributes, it seems reasonable.

**Comment by azhang** [comment]
Awesome, thanks for the feedback! I'll try to add some tests whenever I get the chance and update here.

**Comment by yanickrochon** [comment]
Well, this has been a while! I'm closing this because I have got into another project and had to scrap the whole thing and restart anew. The API changed so much that I am publishing under a different package name, and even host the [project on Gitlab](https://gitlab.com/yanfoo/rbac-a) instead.

See you there, maybe.
